# -*- coding: utf-8 -*-
"""Trabalho Prático.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/109NQhZabDmgSaO7pkWKpFMhLzcO6Z_i8
"""

# VERSAO FINAL
print("""Classificação de Bandas!

        --------- O que deseja fazer?? ---------
        ------ 1. Adicionar nova banda. --------
        ----- 2. Buscar por nome da banda. -----
        --------- 3. Busca avançada. -----------
        ------ 4. Remover banda pelo nome. -----
        ---- 5. Exibir biblioteca completa -----
        ------------- 6. Sair. -----------------



      Por favor, entenda que o catálogo se limita ao registro de 50 bandas.
""")

# LISTA PRINCIPAL
biblioteca_bandas = []

# Inicia o codigo pela escolha do usuario
opcao = int(input("Opção: "))

# Executa ate o usuário optar por sair (opcao 6)
while opcao != 6:

    # Insere um novo registro na lista como um dicionario
    if opcao == 1:
        # Verifica a quantidade dos registros
        if len(biblioteca_bandas) < 50:
            # Valores do dicionario
            banda = {}
            banda["nome"] = input("Nome: ")
            banda["ano"] = int(input("Ano de criação: "))
            banda["genero"] = input("Gênero musical: ")
            banda["arrecadacao"] = float(input("Arrecadação da maior turnê: "))
            banda["album"] = input("Qual o seu álbum favorito? ")

            # Insere no final da lista
            biblioteca_bandas.append(banda)

        # Caso o limite de 50 registros seja atingido
        else:
            print("Limite de bandas atingido. Para continuar, por favor, remova uma banda.")

    # Faz a busca pela chave "nome" dentre as posicoes
    elif opcao == 2:
        # Variavel que vai receber os valores da posicao desejada da lista
        resultado_busca = ""

        buscador_nome = input("Busca por nome selecionada. "
                        "Qual o nome da banda que você está procurando? ")
        cont = 0
        # Variavel para limitar o loop
        i = 0

        # Laco de repeticao que percorre todos os elementos da lista
        while i < len(biblioteca_bandas):
            # Acessa o elemento da lista que estiver na posicao i
            elemento = biblioteca_bandas[i]


            # Compara o nome inserido pelo usuario com a chave nome do dicionario
            if buscador_nome == elemento["nome"]:
                # Quando o resultado for encontrado, a variavel inicial recebe as informacoes do elemento da posicao
                resultado_busca = elemento
                print(f'A banda {resultado_busca["nome"]} foi criada em {resultado_busca["ano"]}. O gênero musical que ela toca é {resultado_busca["genero"]}. A maior arrecadação em turnê foi cerca de R${resultado_busca["arrecadacao"]}. Álbum favorito: {resultado_busca["album"]}.')
                cont += 1
            # a variavel i é iterada ao final de cada repeticao
            i += 1
        # caso nao tenha resultado, o contador nao sai de 0 e esse if eh acionado
        if cont == 0:
            print("Banda não encontrada. Você pode adicioná-la à biblioteca selecionando a Opção 1, se quiser.")


    elif opcao == 3:
        print("""Busca avançada selecionada.
            Para exibir as bandas de acordo com as posições na biblioteca, digite 1.
            Para exibir as bandas do mesmo gênero musical, digite 2.
            Para exibir as bandas com maior arrecadação em turnê, digite 3.""")

        # Input da opcao da busca avancada:
        buscador_avancado = int(input("Opção da busca avançada: "))

        if buscador_avancado == 1:
            # Para determinar o intervalo de posicoes que vai ser exibido:
            inicio = int(input("Posição inicial na biblioteca: "))
            fim = int(input("Posição final na biblioteca: "))

            for i in range(inicio, fim+1):
                elemento = biblioteca_bandas[i]
                print(f'Banda: {elemento["nome"]}, Ano de criação: {elemento["ano"]}, Gênero: {elemento["genero"]}, Arrecadação: {elemento["arrecadacao"]}, Álbum favorito: {elemento["album"]}')

        elif buscador_avancado == 2:
            # O valor do input tem que ser exatamente o mesmo que o registrado na biblioteca
            genero = input("Você quer encontrar bandas de qual gênero musical? ")

            cont = 0
            i = 0
            while i < len(biblioteca_bandas):
                elemento = biblioteca_bandas[i]

                if elemento["genero"] == genero:
                    print(f'{elemento["nome"]}, criada em {elemento["ano"]}. Álbum favorito cadastrado é o {elemento["album"]}')
                    cont += 1
                i += 1

            if cont == 0:
                print("Nenhuma banda do gênero musical informado.")


        # Exibe os elementos que tenham os tres maiores valores de arrecadacao
        elif buscador_avancado == 3:

            primeira = segunda = terceira = ""
            pri_lugar = seg_lugar = terc_lugar = 0

            i = 0

            while i < len(biblioteca_bandas):
                elemento = biblioteca_bandas[i]

                if elemento["arrecadacao"] > pri_lugar:
                    terceira = segunda
                    terc_lugar = seg_lugar

                    segunda = primeira
                    seg_lugar = pri_lugar

                    primeira = elemento["nome"]
                    pri_lugar = elemento["arrecadacao"]

                elif elemento["arrecadacao"] > seg_lugar:
                    terceira = segunda
                    terc_lugar = seg_lugar

                    segunda = elemento["nome"]
                    seg_lugar = elemento["arrecadacao"]

                elif elemento["arrecadacao"] > terc_lugar:
                    terceira = elemento["nome"]
                    terc_lugar = elemento["arrecadacao"]
                i += 1

            print(f"A banda com a maior arrecadação foi: {primeira}, seguida por: {segunda} e {terceira}, respectivamente.")

    # Remove o elemento da lista pelo nome
    elif opcao == 4:
        remocao = input("Informe a banda que deseja remover da biblioteca: ")

        cont = 0
        i = 0
        while i < len(biblioteca_bandas):
            elemento = biblioteca_bandas[i]
            if elemento["nome"] == remocao:
                biblioteca_bandas.remove(elemento)
                cont += 1
            i += 1

        if cont == 0:
            print("Banda não encontrada para remoção.")


    elif opcao == 5:
        if len(biblioteca_bandas) == 0:
            print("Biblioteca vazia. Adicione bandas para começar.")
        else:
            print("A biblioteca completa tem as seguintes bandas: ")
            i = 0

            while i < len(biblioteca_bandas):
                elemento = biblioteca_bandas[i]
                print(f'{elemento["nome"]}, criação: {elemento["ano"]}, gênero musical: {elemento["genero"]}. Maior arrecadação em turnê (em R$){elemento["arrecadacao"]}, Seu álbum favorito: {elemento["album"]}')
                i += 1
    else:
        print("Por favor, escolha uma opção válida conforme o menu!")

    opcao = int(input("Opção: "))

print("Biblioteca encerrada! Volte sempre!")